---
deployment:
  tasks:
    - export DEPLOYPATH=/home/travela3/public_html/
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp  favicon.ico $DEPLOYPATH
    - /bin/cp  index.php $DEPLOYPATH
    - /bin/cp  robots.txt $DEPLOYPATH
    - /bin/cp  web.config $DEPLOYPATH
    - /bin/cp  -R backend $DEPLOYPATH
    - /bin/cp  -R frontend $DEPLOYPATH
    - /bin/cp  -R laravel $DEPLOYPATH
