---
deployment:
  tasks:
    - export DEPLOYPATH=/home/travela3/public_html/
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp  .env $DEPLOYPATH
    - /bin/cp  .env.example $DEPLOYPATH
    - /bin/cp  .gitattributes $DEPLOYPATH
    - /bin/cp  .gitignore $DEPLOYPATH
    - /bin/cp  .styleci.yml $DEPLOYPATH
    - /bin/cp  artisan.php $DEPLOYPATH
    - /bin/cp  composer.json $DEPLOYPATH
    - /bin/cp  composer.lock $DEPLOYPATH
    - /bin/cp  package.json $DEPLOYPATH
    - /bin/cp  phpunit.xml $DEPLOYPATH
    - /bin/cp  README.md $DEPLOYPATH
    - /bin/cp  server.php $DEPLOYPATH
    - /bin/cp  webpack.mix $DEPLOYPATH
    - /bin/cp  -R app $DEPLOYPATH
    - /bin/cp  -R bootstrap $DEPLOYPATH
    - /bin/cp  -R config $DEPLOYPATH
    - /bin/cp  -R database $DEPLOYPATH
    - /bin/cp  -R public $DEPLOYPATH
    - /bin/cp  -R resource $DEPLOYPATH
    - /bin/cp  -R routes $DEPLOYPATH
    - /bin/cp  -R storage $DEPLOYPATH
    - /bin/cp  -R tests $DEPLOYPATH
    - /bin/cp  -R vendor $DEPLOYPATH
